# Generated by Django 4.2.1 on 2023-05-06 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'AdminTable',
            },
        ),
        migrations.CreateModel(
            name='Contactus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('message', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'contactustable',
            },
        ),
        migrations.CreateModel(
            name='JobSeekerRegistration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('phone', models.BigIntegerField(unique=True)),
                ('password', models.CharField(max_length=50)),
                ('registrationtime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'JobSeekerRegistrationTable',
            },
        ),
        migrations.CreateModel(
            name='RecruiterPostedJobs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('openings', models.PositiveIntegerField()),
                ('category', models.CharField(choices=[('fresher', 'Fresher Jobs'), ('marketing', 'Marketing Jobs'), ('contentwriting', 'Content Writing Jobs'), ('hr', 'HR Jobs'), ('datascience', 'Data Science')], max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('all', 'All')], max_length=100)),
                ('description', models.TextField(max_length=200)),
                ('contactdetails', models.EmailField(max_length=50, unique=True)),
                ('minsalary', models.PositiveIntegerField()),
                ('maxsalary', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'RecruiterPostedJobs_table',
            },
        ),
        migrations.CreateModel(
            name='RecruiterRegistration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('phone', models.BigIntegerField(unique=True)),
                ('company', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('hr', 'HR'), ('teamlead', 'TeamLead'), ('manager', 'manager'), ('employee', 'Employee')], max_length=10)),
                ('password', models.CharField(max_length=50)),
                ('registrationtime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'RecruiterRegistrationTable',
            },
        ),
    ]
