# Generated by Django 4.2.1 on 2023-05-06 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seekerapplyforjob',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('phone', models.BigIntegerField(unique=True)),
            ],
            options={
                'db_table': 'Seekerapplyforjob_table',
            },
        ),
    ]
