# Generated by Django 4.2.1 on 2023-05-06 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecsapp', '0002_seekerapplyforjob'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobsPostedByRecruiter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('openings', models.PositiveIntegerField()),
                ('category', models.CharField(choices=[('fresher', 'Fresher Jobs'), ('marketing', 'Marketing Jobs'), ('contentwriting', 'Content Writing Jobs'), ('hr', 'HR Jobs'), ('datascience', 'Data Science')], max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('all', 'All')], max_length=100)),
                ('description', models.TextField(max_length=200)),
                ('contactdetails', models.EmailField(max_length=50, unique=True)),
                ('minsalary', models.PositiveIntegerField()),
                ('maxsalary', models.PositiveIntegerField()),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecsapp.recruiterregistration')),
            ],
            options={
                'db_table': 'JobsPostedByRecruiter_table',
            },
        ),
    ]
