# Generated by Django 4.2.1 on 2023-05-07 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecsapp', '0003_jobspostedbyrecruiter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('age', models.PositiveIntegerField()),
                ('contact', models.BigIntegerField()),
                ('email', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('Others', 'Others')], max_length=100)),
                ('address1', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=200)),
                ('postalcode', models.IntegerField()),
                ('country', models.CharField(max_length=100)),
                ('skills', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Resume_table',
            },
        ),
    ]
