from django.urls import path

from . import views
urlpatterns = [
    path("seekerlogin", views.seekerloginpage, name="seekerlogin"),
    path("seekerregistration", views.seekerregistrationpage, name="seekerregistration"),
    path("checkseekerlogin", views.checkseekerlogin, name="checkseekerlogin"),
    path('seekerlogout', views.seekerlogout, name='seekerlogout'),
    path('seekerhome', views.seekerhome, name='seekerhome'),
    path('seekerjobs', views.seekerjobs, name='seekerjobs'),
    path('resume', views.resumepage, name='resume'),
    path('internships', views.internshipspage, name='internships'),
    path('seekercontact', views.seekercontactpage, name='seekercontact'),
    path('seekerservices', views.seekerservicespage, name='seekerservices'),
    path('seekerprofile', views.seekerprofilepage, name='seekerprofile'),
    path("savejobseekercontct", views.savejobseekercontact, name="savejobseekercontct"),
    path("seekerchangepwd",views.seekerchangepwd,name="seekerchangepwd"),
    path("seekerupdatepwd", views.seekerupdatepwd, name="seekerupdatepwd"),
    path("seekerdashboard", views.seekerdashboard, name="seekerdashboard"),
    path("applypostedjobs", views.applypostedjobs, name="applypostedjobs"),
    path("seekerapplyforjob", views.seekerapplyforjob, name="seekerapplyforjob"),
    path("seekerjobsbycategory", views.seekerjobsbycategory, name="seekerjobsbycategory"),
    path("seekeruploadresume", views.seekeruploadresume, name="seekeruploadresume"),

    path("adminlogin", views.adminloginpage, name="adminlogin"),
    path('checkadminlogin',views.checkadminlogin,name="checkadminlogin"),
    path("adminhome", views.adminhomepage, name="adminhome"),
    path("addseeker", views.addseeker, name="addseeker"),
    path("addrecruiter", views.addrecruiter, name="addrecruiter"),
    path('viewseekerdata',views.viewseekerdata,name="viewseekerdata"),
    path('viewrecruiterdata', views.viewrecruiterdata, name="viewrecruiterdata"),
    path('updateseeker', views.updateseeker, name="updateseeker"),
    path('updaterecruiter',views.updaterecruiter, name="updaterecruiter"),
    path("deleteseeker/<int:eid>", views.deleteseeker, name="deleteseeker"),
    path('adminlogout', views.adminlogout, name='adminlogout'),

    path("recruiterlogin", views.recruiterloginpage, name="recruiterlogin"),
    path("recruiterregistration", views.recruiterregistrationpage, name="recruiterregistration"),
    path('checkrecruiterlogin',views.checkrecruiterlogin,name="checkrecruiterlogin"),
    path("recruiterhome", views.recruiterhomepage, name="recruiterhome"),
    path("newapplicants", views.newapplicants, name="newapplicants"),
    path("addcandidate", views.addcandidate, name="addcandidate"),
    path("managecandidate", views.managecandidate, name="managecandidate"),
    path("searchresume", views.searchresume, name="searchresume"),
    path("addinterview", views.addinterview, name="addinterview"),
    path("interviewlist", views.interviewlist, name="interviewlist"),
    path("recruitercontact", views.recruitercontact, name="recruitercontact"),
    path("recruiterprofile", views.recruiterprofile, name="recruiterprofile"),
    path("recruiterlogout", views.recruiterlogout, name="recruiterlogout"),
    path("postjob", views.postjob, name="postjob"),
    path("recruiterchangepwd",views.recruiterchangepwd,name="recruiterchangepwd"),
    path("recruiterupdatepwd", views.recruiterupdatepwd, name="recruiterupdatepwd"),
    path("recruitermanagejobs", views.recruitermanagejobs, name="recruitermanagejobs"),
    path("deleterecruiter/<int:eid>", views.deleterecruiter, name="deleterecruiter"),
    path("deletepostedjobs/<int:eid>", views.deletepostedjobs, name="deletepostedjobs"),

]